import './components/beam-app.js';
import './components/beam-sidebar.js';
import './components/method-card.js';
import './components/invoke-form.js';
import './components/activity-log.js';
import './components/result-viewer.js';
import './components/file-picker.js';
import './components/marketplace-view.js';
import './components/custom-ui-renderer.js';
import './components/mcp-app-renderer.js';
import './components/toast-manager.js';
import './components/photon-studio.js';
import './components/studio-preview.js';
import './components/photon-config.js';
import './components/elicitation-modal.js';
import './components/overflow-menu.js';
import './components/context-bar.js';
import './components/app-layout.js';

console.log('✨ Beam UI Initialized');
