/**
 * Input validation utilities
 * Re-exported from @portel/photon-core
 */
export {
  type ValidationResult,
  type Validator,
  combineResults,
  isString,
  isNumber,
  isBoolean,
  isObject,
  isArray,
  notEmpty,
  hasLength,
  matchesPattern,
  isEmail,
  isUrl,
  inRange,
  isPositive,
  isInteger,
  hasArrayLength,
  arrayOf,
  hasFields,
  oneOf,
  validate,
  validateOrThrow,
  pathExists,
  hasExtension,
  assertDefined,
  assertString,
  assertNumber,
  assertObject,
  assertArray,
} from '@portel/photon-core';
