import * as path from 'path';
import { mkdir, writeFile } from 'fs/promises';

import { getDefaultContext } from './context.js';

const DECLARATION_CACHE_SUBDIR = ['.cache', 'photon-types'];

function toPosix(p: string): string {
  return p.replace(/\\/g, '/');
}

function sanitizeExternalPath(sourcePath: string): string {
  return sourcePath
    .replace(/^([A-Za-z]):/, '$1')
    .replace(/^[\\/]+/, '')
    .replace(/[\\/]+/g, '/')
    .replace(/[^A-Za-z0-9._/-]/g, '_');
}

function relativeSourceKey(sourcePath: string, baseDir: string): string {
  const rel = path.relative(baseDir, sourcePath);
  if (!rel.startsWith('..') && !path.isAbsolute(rel)) {
    return rel;
  }
  return path.join('_external', sanitizeExternalPath(sourcePath));
}

function moduleSpecifier(fromFile: string, toFile: string): string {
  let rel = path.relative(path.dirname(fromFile), toFile);
  rel = rel.replace(/\.(ts|js|mts|cts|mjs|cjs)$/i, '');
  rel = toPosix(rel);
  return rel.startsWith('.') ? rel : `./${rel}`;
}

export function getPhotonEditorDeclarationPath(
  sourcePath: string,
  baseDir = getDefaultContext().baseDir
): string {
  const rel = relativeSourceKey(sourcePath, baseDir);
  const parsed = path.parse(rel);
  return path.join(
    baseDir,
    ...DECLARATION_CACHE_SUBDIR,
    parsed.dir,
    `${parsed.name}.generated.d.ts`
  );
}

export function buildPhotonEditorDeclaration(
  sourcePath: string,
  source: string,
  baseDir = getDefaultContext().baseDir
): string | null {
  const classMatch = source.match(/export\s+default\s+class\s+([A-Za-z_$][\w$]*)/);
  if (!classMatch) return null;

  const className = classMatch[1];
  const declarationPath = getPhotonEditorDeclarationPath(sourcePath, baseDir);
  const sourceModule = moduleSpecifier(declarationPath, sourcePath);

  return `// Auto-generated by Photon Beam. Do not edit manually.
import type { Photon } from '@portel/photon-core';

declare module '${sourceModule}' {
  interface ${className} extends Photon {}
}

export {};
`;
}

export async function writePhotonEditorDeclaration(
  sourcePath: string,
  source: string,
  baseDir = getDefaultContext().baseDir
): Promise<string | null> {
  const content = buildPhotonEditorDeclaration(sourcePath, source, baseDir);
  if (!content) return null;

  const declarationPath = getPhotonEditorDeclarationPath(sourcePath, baseDir);
  await mkdir(path.dirname(declarationPath), { recursive: true });
  await writeFile(declarationPath, content, 'utf-8');
  return declarationPath;
}
